# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  api:
    image: api:dev
    build:
      context: .
      dockerfile: Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5000:5000
    networks:
      - sql-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZURE_FUNCTIONS_ENVIRONMENT=Development
      - ConnectionString=server=sql-server,1433;User Id=sa;Password=Admin1234;Database=api-db;TrustServerCertificate=true
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
    tty: true # Habilita interação entre o terminal do host e o do container
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Admin1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - sql-network


networks: 
  sql-network:
    driver: bridge