# Yml destinado a depuração local

# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  api:
    image: api:dev
    build:
      context: .
      dockerfile: Api/Dockerfile
      args:
        - configuration=Debug
        - BUILD_CONFIGURATION=Debug
    ports:
      - 7071:7071
    networks:
      - sql-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZURE_FUNCTIONS_ENVIRONMENT=Development
      - ConnectionString=server=sql-server,1433;User Id=sa;Password=Admin1234;Database=api-db;TrustServerCertificate=true
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - FUNCTIONS_ENABLE_DEBUGGER_WAIT=True

    entrypoint: sh -c "/functions_debugging_cli/func host start --no-build --dotnet-isolated-debug --enable-json-output" #Inicia o azure functions em modo debug
    volumes:
      - C:\Users\marco\Desktop\Code\Locus\Api:/home/site/wwwroot
      - C:\Users\marco\Desktop\Code\Locus:/src
      - ~/.vsdbg:/remote_debugger:rw
      - C:\Users\marco\AppData\Local\AzureFunctionsTools\Releases\4.69.0\cli_x64_Linux:/functions_debugging_cli:ro # Mapeia as ferramentas do azure do pc do host para o container. 
      - C:\Users\marco\.nuget\packages\:/.nuget/packages:ro
      # - C:\Users\marco\Desktop\Code\Locus\Api:/home/site/wwwroot
      # - C:\Users\marco\Desktop\Code\Locus:/src
    tty: true # Habilita interação entre o terminal do host e o do container
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Admin1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - sql-network


networks: 
  sql-network:
    driver: bridge