# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  api:
    image: api:dev
    build:
      context: .
      dockerfile: Api/Dockerfile
      args:
        - configuration=Debug
        - BUILD_CONFIGURATION=Debug
    ports:
      - 7071:7071
    networks:
      - sql-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZURE_FUNCTIONS_ENVIRONMENT=Development
      - ConnectionString=server=sql-server,1433;User Id=sa;Password=Admin1234;Database=api-db;TrustServerCertificate=true
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
    entrypoint: sh -c "cd /ApiDebug && pwd && ls && /functions_debugging_cli/func host start --dotnet-isolated-debug --no-build --enable-json-output" #Inicia o azure functions em modo debug
    volumes:
      - C:\Users\marco\Desktop\Code\Locus\Api\bin\Debug\net8.0:/ApiDebug
      - ~/.vsdbg:/remote_debugger:rw
      - C:\Users\marco\AppData\Local\AzureFunctionsTools\Releases\4.69.0\cli_x64_Linux:/functions_debugging_cli:ro # Mapeia as ferramentas do azure do pc do host para o container. 
    tty: true # Habilita interação entre o terminal do host e o do container
    labels:
      killprogram: "/bin/sh -c 'if PID=$$(pidof dotnet); then kill -9 $$PID; fi; if PID1=$$(pidof func); then kill -9 $$PID1; fi'"
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Admin1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - sql-network


networks: 
  sql-network:
    driver: bridge